FROM python:3.9-slim

WORKDIR /app

COPY . .

ENV DB_HOST=172.20.0.10
ENV DB_TABLE=${MYSQL_TABLE}
ENV DB_USER=${MYSQL_USER}
ENV DB_NAME=${MYSQL_DATABASE}
ENV DB_PASSWORD=${MYSQL_PASSWORD}

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]